format = """$all"""

[shell]
disabled = false

[username]
show_always = true

[hostname]
ssh_only = false
ssh_symbol = "ssh:"
format = "on [$ssh_symbol$hostname]($style) "

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
